apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicecamp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dicecamp
  template:
    metadata:
      labels:
        app: dicecamp
    spec:
      containers:
      - name: dicecamp
        image: dicecamp:1.0
        ports:
        - containerPort: 80
